services: 
  db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - TZ=${TZ} 
      - PUID=${PUID} 
      - PGID=${PGID} 
      - MYSQL_USER=${MYSQL_USER} 
      - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD} 
      - MYSQL_PASSWORD=${DATABASE_PASSWORD} 
      - MYSQL_DATABASE=${USER_DB_NAME}   

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro

  nextcloud:
    depends_on:
      - redis
      - db
    image: linuxserver/nextcloud:latest 
    container_name: nextcloud
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./data:/data"
    networks:
      - traefik_proxy
      - default
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAINNAME}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-regex,nextcloud-headers"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=websecure"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-regex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"

networks:
  traefik_proxy:
    external: true

volumes:
  nextcloud-db: