volumes:
  nextcloud:
  db:
  redis:

services:
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data  

  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - 8080:80
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db


# services: 
#   db:
#     image: mariadb:latest
#     container_name: nextcloud_db
#     volumes:
#       - nextcloud-db:/var/lib/mysql
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - default
#     security_opt:
#       - no-new-privileges:true
#     restart: always
#     environment:
#       - TZ=${TZ} 
#       - PUID=${PUID} 
#       - PGID=${PGID} 
#       - MYSQL_USER=${MYSQL_USER} 
#       - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD} 
#       - MYSQL_PASSWORD=${DATABASE_PASSWORD} 
#       - MYSQL_DATABASE=${USER_DB_NAME}   

#   redis:
#     image: redis:alpine
#     container_name: nextcloud_redis
#     restart: always
#     networks:
#       - default
#     security_opt:
#       - no-new-privileges:true
#     volumes:
#       - /etc/localtime:/etc/localtime:ro

#   nextcloud:
#     depends_on:
#       - redis
#       - db
#     image: nextcloud:latest 
#     container_name: nextcloud
#     hostname: nextcloud.${DOMAINNAME}
#     volumes:
#       - "/etc/localtime:/etc/localtime:ro"
#       - "./config:/config"
#       - "./data:/data"
#     networks:
#       - traefik_proxy
#       - default
#     security_opt:
#       - no-new-privileges:true
#     restart: always
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TZ}
#     labels:
#       - "traefik.enable=true"
#       - "traefik.docker.network=traefik_proxy"
#       - "traefik.http.routers.nextcloud.rule=Host(`nextcloud..${DOMAINNAME}`)"
#       - "traefik.http.routers.nextcloud.entrypoints=websecure"
#       - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
#       - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

# networks:
#   traefik_proxy:
#     external: true

# volumes:
#   nextcloud-db: