global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'