services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      GAMEMODE: "survival"
      DIFFICULTY: "easy"
      SERVER_NAME: "Smashtopia"
      LEVEL_NAME: "Pizzaville"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true